### PR TITLE
fix: deleting listeners from event stream pagination

### PR DESCRIPTION
**Pull request by EnriqueL8**
When deleting an event stream that has more listeners that the default pagination limit, it was failing due to incorrect logic of deleting the listener before using it as "offset" to query the next set of listeners to delete.

This PR fixes this by querying the next set before deleting the last one.

### CODE REVIEW

**Comment by EnriqueL8** [comment]
Tested locally with a custom build of evmconnect in FF CLI

**Review by peterbroadhurst — CHANGES_REQUESTED** [review]
We shouldn't need to duplicate code to fix the bug here

**Comment by EnriqueL8** [comment]
Thanks for the pointer @peterbroadhurst - radically simpler now

**Review by peterbroadhurst — APPROVED** [review]
Thanks for the extra go-round to simplify @EnriqueL8

**Pull request merged**
